/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oca.project;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oca.project.managers.Manager;

/**
 *
 * @author 92016097
 */
public class assignBonusForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public assignBonusForm(){
        initComponents();
        getContentPane().setBackground(new Color(16,188,212));
        Employees employees = OCAProject.getEmployees();
        IManager[] managers = employees.getManagers();
        for (IManager manager : managers) {
            cboManager.addItem(manager);
        }
        ArrayList<ISubordinate> subordinates =  new ArrayList<>();
        subordinates.addAll(subordinates);
        for(ISubordinate subordinate : subordinates) {
            cboSubordinates.addItem(subordinate);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        btnAssignBonus1 = new javax.swing.JButton();
        btnDetails_DataEntry1 = new javax.swing.JButton();
        btnRun_Reports1 = new javax.swing.JButton();
        btnClose1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblBestITPayroll1 = new javax.swing.JLabel();
        btnAssignBonus = new javax.swing.JButton();
        btnCheckCurrentBonus = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cboManager = new javax.swing.JComboBox();
        cboSubordinates = new javax.swing.JComboBox();
        txtBonus = new javax.swing.JTextField();
        lblManager = new javax.swing.JLabel();
        lblSubordinates = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setAutoRequestFocus(false);
        jFrame1.setBackground(new java.awt.Color(16, 188, 212));

        btnAssignBonus1.setBackground(new java.awt.Color(68, 199, 54));
        btnAssignBonus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssignBonus1.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignBonus1.setMnemonic('a');
        btnAssignBonus1.setText("Assign Bonus");

        btnDetails_DataEntry1.setBackground(new java.awt.Color(68, 199, 54));
        btnDetails_DataEntry1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetails_DataEntry1.setForeground(new java.awt.Color(255, 255, 255));
        btnDetails_DataEntry1.setMnemonic('p');
        btnDetails_DataEntry1.setText("Personal Details and Contractor Data Entry");

        btnRun_Reports1.setBackground(new java.awt.Color(68, 199, 54));
        btnRun_Reports1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRun_Reports1.setForeground(new java.awt.Color(255, 255, 255));
        btnRun_Reports1.setMnemonic('r');
        btnRun_Reports1.setText("Run Reports");

        btnClose1.setBackground(new java.awt.Color(102, 102, 102));
        btnClose1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose1.setForeground(new java.awt.Color(255, 255, 255));
        btnClose1.setMnemonic('c');
        btnClose1.setText("Close");

        jPanel2.setBackground(new java.awt.Color(65, 65, 65));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblBestITPayroll1.setFont(new java.awt.Font("Maiandra GD", 1, 53)); // NOI18N
        lblBestITPayroll1.setForeground(new java.awt.Color(255, 255, 255));
        lblBestITPayroll1.setText("Best IT Payroll");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(lblBestITPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBestITPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRun_Reports1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetails_DataEntry1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssignBonus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAssignBonus1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetails_DataEntry1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRun_Reports1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(16, 188, 212));
        setResizable(false);

        btnAssignBonus.setBackground(new java.awt.Color(68, 199, 54));
        btnAssignBonus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssignBonus.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignBonus.setMnemonic('a');
        btnAssignBonus.setText("Assign Bonus");
        btnAssignBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignBonusActionPerformed(evt);
            }
        });

        btnCheckCurrentBonus.setBackground(new java.awt.Color(68, 199, 54));
        btnCheckCurrentBonus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCheckCurrentBonus.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckCurrentBonus.setMnemonic('c');
        btnCheckCurrentBonus.setText("Check Current Bonus");
        btnCheckCurrentBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckCurrentBonusActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setMnemonic('b');
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cboManager.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboManagerItemStateChanged(evt);
            }
        });
        cboManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboManagerActionPerformed(evt);
            }
        });

        cboSubordinates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubordinatesActionPerformed(evt);
            }
        });

        lblManager.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblManager.setForeground(new java.awt.Color(255, 255, 255));
        lblManager.setText("Manager:");

        lblSubordinates.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSubordinates.setForeground(new java.awt.Color(255, 255, 255));
        lblSubordinates.setText("Subordinates list:");

        lblBonus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblBonus.setForeground(new java.awt.Color(255, 255, 255));
        lblBonus.setText("Bonus:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oca/project/AssignBonus.jpg"))); // NOI18N
        jLabel1.setText("lblAssignBonus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboManager, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboSubordinates, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblBonus)
                            .addComponent(lblManager)
                            .addComponent(lblSubordinates)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAssignBonus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCheckCurrentBonus, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)))))
                .addGap(129, 139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManager))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSubordinates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubordinates))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBonus))
                .addGap(46, 46, 46)
                .addComponent(btnAssignBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckCurrentBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        mainForm form = new mainForm();
        form.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cboManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboManagerActionPerformed

    private void cboManagerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboManagerItemStateChanged
        cboSubordinates.removeAllItems();
        IManager selectedManager = (IManager) cboManager.getSelectedItem();
        ArrayList<ISubordinate> subordinates = selectedManager.getSubordinateList();
                int numOfSalariedSubordinates = 0;
        for (ISubordinate subordinate : subordinates) {
            if(subordinate instanceof ISalariedPerson) {
                numOfSalariedSubordinates++;
            }
        }
        if(numOfSalariedSubordinates == 0) {
            cboSubordinates.addItem("No Salaried Subordinates");
        }
        else {
            for(ISubordinate subordinate : subordinates) {
                cboSubordinates.addItem(subordinate);
            }
        }
    }//GEN-LAST:event_cboManagerItemStateChanged

    private void cboSubordinatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubordinatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSubordinatesActionPerformed

    private void btnAssignBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignBonusActionPerformed
        String jOptionPaneMessage = "";
        if (cboManager.getSelectedItem() instanceof CEO) {
            CEO ceo = (CEO) cboManager.getSelectedItem();
            try {
                jOptionPaneMessage = ceo.assignBonus( (ISubordinate) cboSubordinates.getSelectedItem(), Double.parseDouble(txtBonus.getText()));
            }
            catch(NumberFormatException nfe) {
                jOptionPaneMessage = "Please enter a valid amount.";
                txtBonus.requestFocusInWindow();
                txtBonus.selectAll();
            }
            finally {
                JOptionPane.showMessageDialog(this, jOptionPaneMessage, "Announcement", JOptionPane.INFORMATION_MESSAGE);
                txtBonus.requestFocusInWindow();
                txtBonus.selectAll();
            }
        }
        else {
            Manager manager = (Manager) cboManager.getSelectedItem();
            try {
                jOptionPaneMessage = manager.assignBonus((ISubordinate) cboSubordinates.getSelectedItem(), Double.parseDouble(txtBonus.getText()));
            }
            catch (NumberFormatException nfe) {
                jOptionPaneMessage = "Please enter a valid amount.";
                txtBonus.requestFocusInWindow();
                txtBonus.selectAll();
            }
            finally {
                JOptionPane.showMessageDialog(this, jOptionPaneMessage, "Announcement", JOptionPane.INFORMATION_MESSAGE);
                txtBonus.requestFocusInWindow();
                txtBonus.selectAll();
            }
        }
    }//GEN-LAST:event_btnAssignBonusActionPerformed

    private void btnCheckCurrentBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckCurrentBonusActionPerformed
        if((cboSubordinates.getSelectedItem() instanceof ISalariedPerson) == false) {
            JOptionPane.showMessageDialog(this, cboSubordinates.getSelectedItem() + " is a contractor and cannot be allocated a bonus.", "Announcement", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            ISalariedPerson employee = (ISalariedPerson) cboSubordinates.getSelectedItem();
            JOptionPane.showMessageDialog(this, employee + "'s current bonus: $" + employee.getCurrentBonus(), "Employee Bonus", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckCurrentBonusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assignBonusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assignBonusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assignBonusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assignBonusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new assignBonusForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignBonus;
    private javax.swing.JButton btnAssignBonus1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckCurrentBonus;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnDetails_DataEntry1;
    private javax.swing.JButton btnRun_Reports1;
    private javax.swing.JComboBox cboManager;
    private javax.swing.JComboBox cboSubordinates;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBestITPayroll1;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblManager;
    private javax.swing.JLabel lblSubordinates;
    private javax.swing.JTextField txtBonus;
    // End of variables declaration//GEN-END:variables
}
