/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oca.project;

import java.awt.Color;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 92016097
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
        getContentPane().setBackground(new Color(16,188,212));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        btnAssignBonus1 = new javax.swing.JButton();
        btnDetails_DataEntry1 = new javax.swing.JButton();
        btnRun_Reports1 = new javax.swing.JButton();
        btnClose1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblBestITPayroll1 = new javax.swing.JLabel();
        btnAssignBonus = new javax.swing.JButton();
        btnDetails_DataEntry = new javax.swing.JButton();
        btnRun_Reports = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblBestITPayroll = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setAutoRequestFocus(false);
        jFrame1.setBackground(new java.awt.Color(16, 188, 212));

        btnAssignBonus1.setBackground(new java.awt.Color(68, 199, 54));
        btnAssignBonus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssignBonus1.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignBonus1.setMnemonic('a');
        btnAssignBonus1.setText("Assign Bonus");

        btnDetails_DataEntry1.setBackground(new java.awt.Color(68, 199, 54));
        btnDetails_DataEntry1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetails_DataEntry1.setForeground(new java.awt.Color(255, 255, 255));
        btnDetails_DataEntry1.setMnemonic('p');
        btnDetails_DataEntry1.setText("Personal Details and Contractor Data Entry");

        btnRun_Reports1.setBackground(new java.awt.Color(68, 199, 54));
        btnRun_Reports1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRun_Reports1.setForeground(new java.awt.Color(255, 255, 255));
        btnRun_Reports1.setMnemonic('r');
        btnRun_Reports1.setText("Run Reports");

        btnClose1.setBackground(new java.awt.Color(102, 102, 102));
        btnClose1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose1.setForeground(new java.awt.Color(255, 255, 255));
        btnClose1.setMnemonic('c');
        btnClose1.setText("Close");

        jPanel2.setBackground(new java.awt.Color(65, 65, 65));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblBestITPayroll1.setFont(new java.awt.Font("Maiandra GD", 1, 53)); // NOI18N
        lblBestITPayroll1.setForeground(new java.awt.Color(255, 255, 255));
        lblBestITPayroll1.setText("Best IT Payroll");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(lblBestITPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBestITPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRun_Reports1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetails_DataEntry1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssignBonus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAssignBonus1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetails_DataEntry1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRun_Reports1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(16, 188, 212));
        setResizable(false);

        btnAssignBonus.setBackground(new java.awt.Color(68, 199, 54));
        btnAssignBonus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssignBonus.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignBonus.setMnemonic('a');
        btnAssignBonus.setText("Assign Bonus");
        btnAssignBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignBonusActionPerformed(evt);
            }
        });

        btnDetails_DataEntry.setBackground(new java.awt.Color(68, 199, 54));
        btnDetails_DataEntry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetails_DataEntry.setForeground(new java.awt.Color(255, 255, 255));
        btnDetails_DataEntry.setMnemonic('p');
        btnDetails_DataEntry.setText("Personal Details and Contractor Data Entry");
        btnDetails_DataEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetails_DataEntryActionPerformed(evt);
            }
        });

        btnRun_Reports.setBackground(new java.awt.Color(68, 199, 54));
        btnRun_Reports.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRun_Reports.setForeground(new java.awt.Color(255, 255, 255));
        btnRun_Reports.setMnemonic('r');
        btnRun_Reports.setText("Run Reports");
        btnRun_Reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRun_ReportsActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(102, 102, 102));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setMnemonic('c');
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblBestITPayroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oca/project/BestITPayroll.jpg"))); // NOI18N
        lblBestITPayroll.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRun_Reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetails_DataEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssignBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBestITPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblBestITPayroll)
                .addGap(62, 62, 62)
                .addComponent(btnAssignBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetails_DataEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnRun_Reports, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAssignBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignBonusActionPerformed
        this.dispose();
        assignBonusForm form = new assignBonusForm();
        form.setVisible(true);
    }//GEN-LAST:event_btnAssignBonusActionPerformed

    private void btnDetails_DataEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetails_DataEntryActionPerformed
        this.dispose();
        Details_DataEntryForm form;
        try {
            form = new Details_DataEntryForm();
            form.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDetails_DataEntryActionPerformed

    private void btnRun_ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRun_ReportsActionPerformed
        this.dispose();
        PayrollReportsForm form = new PayrollReportsForm();
        form.setVisible(true);
    }//GEN-LAST:event_btnRun_ReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignBonus;
    private javax.swing.JButton btnAssignBonus1;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnDetails_DataEntry;
    private javax.swing.JButton btnDetails_DataEntry1;
    private javax.swing.JButton btnRun_Reports;
    private javax.swing.JButton btnRun_Reports1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBestITPayroll;
    private javax.swing.JLabel lblBestITPayroll1;
    // End of variables declaration//GEN-END:variables
}
