/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oca.project;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author 92016097
 */
public class PayrollReportsForm extends javax.swing.JFrame {
    private SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
    private Date date1;
    private Date date2;
    private ArrayList<ISalariedPerson> arrayOfEmployees;
    private ISalariedPerson[] salariedEmployees;
    private IPaidPerson[] contractedEmployees;
    private String output = "";
    Employees employees;
    private IPaidPerson[] listOfEmployees;
    private static ArrayList<PayrollReportItem> payRollReportItems = new ArrayList<PayrollReportItem>();
    /**
     * Creates new form mainForm
     */
    public PayrollReportsForm() {
        initComponents();
        getContentPane().setBackground(new Color(16,188,212));
        employees = OCAProject.getEmployees();
        listOfEmployees = employees.getAllEmployees();
        for(IPaidPerson person : listOfEmployees) {
            if (person instanceof CEO == false) {
                cboName.addItem(person);
            }
        }
        arrayOfEmployees = new ArrayList<>();
        salariedEmployees = employees.getSalariedEmployees();
        contractedEmployees = employees.getContractedEmployees();
    }

    public static void setpayRollReportItems(PayrollReportItem payRollReportItems) {
        PayrollReportsForm.payRollReportItems.add(payRollReportItems);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        btnAssignBonus1 = new javax.swing.JButton();
        btnDetails_DataEntry1 = new javax.swing.JButton();
        btnRun_Reports1 = new javax.swing.JButton();
        btnClose1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblBestITPayroll1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblFirstDate = new javax.swing.JLabel();
        lblSecondDate = new javax.swing.JLabel();
        txtSecondDate = new javax.swing.JTextField();
        cboName = new javax.swing.JComboBox();
        txtFirstDate = new javax.swing.JTextField();
        btnAllPaymentsPeriod = new javax.swing.JButton();
        btnFortnightlyPayments = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnBonusesReport1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnPaymentHistoryPerson1 = new javax.swing.JButton();
        btnMonthlyPayments = new javax.swing.JButton();
        txtOutputPane = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        lblPayrollReports = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setAutoRequestFocus(false);
        jFrame1.setBackground(new java.awt.Color(16, 188, 212));

        btnAssignBonus1.setBackground(new java.awt.Color(68, 199, 54));
        btnAssignBonus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssignBonus1.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignBonus1.setMnemonic('a');
        btnAssignBonus1.setText("Assign Bonus");

        btnDetails_DataEntry1.setBackground(new java.awt.Color(68, 199, 54));
        btnDetails_DataEntry1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetails_DataEntry1.setForeground(new java.awt.Color(255, 255, 255));
        btnDetails_DataEntry1.setMnemonic('p');
        btnDetails_DataEntry1.setText("Personal Details and Contractor Data Entry");

        btnRun_Reports1.setBackground(new java.awt.Color(68, 199, 54));
        btnRun_Reports1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRun_Reports1.setForeground(new java.awt.Color(255, 255, 255));
        btnRun_Reports1.setMnemonic('r');
        btnRun_Reports1.setText("Run Reports");

        btnClose1.setBackground(new java.awt.Color(102, 102, 102));
        btnClose1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose1.setForeground(new java.awt.Color(255, 255, 255));
        btnClose1.setMnemonic('c');
        btnClose1.setText("Close");

        jPanel2.setBackground(new java.awt.Color(65, 65, 65));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblBestITPayroll1.setFont(new java.awt.Font("Maiandra GD", 1, 53)); // NOI18N
        lblBestITPayroll1.setForeground(new java.awt.Color(255, 255, 255));
        lblBestITPayroll1.setText("Best IT Payroll");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(lblBestITPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBestITPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRun_Reports1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetails_DataEntry1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssignBonus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAssignBonus1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetails_DataEntry1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRun_Reports1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(16, 188, 212));
        setResizable(false);

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setMnemonic('b');
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFirstDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFirstDate.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstDate.setText("First Date:");

        lblSecondDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSecondDate.setForeground(new java.awt.Color(255, 255, 255));
        lblSecondDate.setText("Second Date:");

        cboName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNameActionPerformed(evt);
            }
        });

        btnAllPaymentsPeriod.setBackground(new java.awt.Color(68, 199, 54));
        btnAllPaymentsPeriod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAllPaymentsPeriod.setForeground(new java.awt.Color(255, 255, 255));
        btnAllPaymentsPeriod.setMnemonic('a');
        btnAllPaymentsPeriod.setText("All payment for a period");
        btnAllPaymentsPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllPaymentsPeriodActionPerformed(evt);
            }
        });

        btnFortnightlyPayments.setBackground(new java.awt.Color(68, 199, 54));
        btnFortnightlyPayments.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFortnightlyPayments.setForeground(new java.awt.Color(255, 255, 255));
        btnFortnightlyPayments.setMnemonic('f');
        btnFortnightlyPayments.setText("Fortnightly payments");
        btnFortnightlyPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFortnightlyPaymentsActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnBonusesReport1.setBackground(new java.awt.Color(68, 199, 54));
        btnBonusesReport1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBonusesReport1.setForeground(new java.awt.Color(255, 255, 255));
        btnBonusesReport1.setMnemonic('b');
        btnBonusesReport1.setText("Bonuses report");
        btnBonusesReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBonusesReport1ActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        btnPaymentHistoryPerson1.setBackground(new java.awt.Color(68, 199, 54));
        btnPaymentHistoryPerson1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPaymentHistoryPerson1.setForeground(new java.awt.Color(255, 255, 255));
        btnPaymentHistoryPerson1.setMnemonic('p');
        btnPaymentHistoryPerson1.setText("Payment history by person");
        btnPaymentHistoryPerson1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentHistoryPerson1ActionPerformed(evt);
            }
        });

        btnMonthlyPayments.setBackground(new java.awt.Color(68, 199, 54));
        btnMonthlyPayments.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMonthlyPayments.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthlyPayments.setMnemonic('m');
        btnMonthlyPayments.setText("Monthly payments");
        btnMonthlyPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyPaymentsActionPerformed(evt);
            }
        });

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        txtOutputPane.setViewportView(txtOutput);

        lblPayrollReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oca/project/PayrollReports.jpg"))); // NOI18N
        lblPayrollReports.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSecondDate)
                                    .addComponent(lblFirstDate))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtSecondDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstDate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBonusesReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFortnightlyPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMonthlyPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAllPaymentsPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(btnPaymentHistoryPerson1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(txtOutputPane, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPayrollReports, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblPayrollReports)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstDate)
                            .addComponent(txtFirstDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSecondDate)
                            .addComponent(txtSecondDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAllPaymentsPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBonusesReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(cboName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPaymentHistoryPerson1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFortnightlyPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMonthlyPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtOutputPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        mainForm form = new mainForm();
        form.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBonusesReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBonusesReport1ActionPerformed
        txtOutput.setText("");
        for (ISalariedPerson employee : salariedEmployees) {
            arrayOfEmployees.add(employee);
        }
        for(ISalariedPerson employee : arrayOfEmployees) {
            Person person = (Person) employee;
            if(employee.getCurrentBonus() > 0) {
                txtOutput.setText(txtOutput.getText() + person.getName() + " has a bonus of $" + employee.getCurrentBonus() + "\n");
            }
        }
        arrayOfEmployees.clear();
        
    }//GEN-LAST:event_btnBonusesReport1ActionPerformed

    private void btnAllPaymentsPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllPaymentsPeriodActionPerformed
        txtOutput.setText("");
        String output = "";
        try {
            date1 = dateFormatter.parse(txtFirstDate.getText());
            date2 = dateFormatter.parse(txtSecondDate.getText());
            for (PayrollReportItem item : PayrollReportsForm.payRollReportItems) {
                if (item.getStartOfPayPeriod().before(date1) == true  && item.getStartOfPayPeriod().after(date2) == true) {
                    output += item.toString() + "\n";
                }
                output += item.toString() + "\n";
        }
        } catch (ParseException ex) {
            Logger.getLogger(PayrollReportsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtOutput.setText(output);  
    }//GEN-LAST:event_btnAllPaymentsPeriodActionPerformed

    private void btnFortnightlyPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFortnightlyPaymentsActionPerformed
        String output = "";
        txtOutput.setText("");
        for (PayrollReportItem item : PayrollReportsForm.payRollReportItems) {
            if (item.getTimePeriod() != TimePeriods.MONTHLY) {
                output += item.toString() + "\n";
            }
        }
        txtOutput.setText(output);
    }//GEN-LAST:event_btnFortnightlyPaymentsActionPerformed

    private void btnMonthlyPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyPaymentsActionPerformed
        String output = "";
        txtOutput.setText("");
        for (PayrollReportItem item : PayrollReportsForm.payRollReportItems) {
            if (item.getTimePeriod() != TimePeriods.FORTNIGHTLY) {
                output += item.toString() + "\n";
            }
        }
        txtOutput.setText(output);
    }//GEN-LAST:event_btnMonthlyPaymentsActionPerformed

    private void btnPaymentHistoryPerson1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentHistoryPerson1ActionPerformed
        String output = "";
        String selectedName = ((String) cboName.getSelectedItem().toString());
        txtOutput.setText("");
        for (PayrollReportItem item : PayrollReportsForm.payRollReportItems) {
            if (item.getName().equals(selectedName)) {
                output += item.toString() + "\n";
            }
        }
        txtOutput.setText(output);
        
    }//GEN-LAST:event_btnPaymentHistoryPerson1ActionPerformed

    private void cboNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollReportsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllPaymentsPeriod;
    private javax.swing.JButton btnAssignBonus1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBonusesReport1;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnDetails_DataEntry1;
    private javax.swing.JButton btnFortnightlyPayments;
    private javax.swing.JButton btnMonthlyPayments;
    private javax.swing.JButton btnPaymentHistoryPerson1;
    private javax.swing.JButton btnRun_Reports1;
    private javax.swing.JComboBox cboName;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBestITPayroll1;
    private javax.swing.JLabel lblFirstDate;
    private javax.swing.JLabel lblPayrollReports;
    private javax.swing.JLabel lblSecondDate;
    private javax.swing.JTextField txtFirstDate;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JScrollPane txtOutputPane;
    private javax.swing.JTextField txtSecondDate;
    // End of variables declaration//GEN-END:variables
}
